# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfvm < Formula
  desc "A Terraform Version Manager written in Go"
  homepage "https://github.com/ethanhassett/tfvm/tree/main"
  version "1.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ehassett/tfvm/releases/download/v1.3.2/tfvm_1.3.2_darwin_amd64.tar.gz"
      sha256 "c9838b9415bfcc6f73d784d747a99e3a70b6cfa29ed756db4a60b64a441e9ee1"

      def install
        bin.install "tfvm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ehassett/tfvm/releases/download/v1.3.2/tfvm_1.3.2_darwin_arm64.tar.gz"
      sha256 "1bde1bccd24f1b01b17eaad568a264d351976c3416b07586e82a9e3e7bfca1c5"

      def install
        bin.install "tfvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ehassett/tfvm/releases/download/v1.3.2/tfvm_1.3.2_linux_amd64.tar.gz"
      sha256 "5e60097d02b749bd1df366989d9fe83282aaf172c711a2464380515c7c65d292"

      def install
        bin.install "tfvm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ehassett/tfvm/releases/download/v1.3.2/tfvm_1.3.2_linux_arm64.tar.gz"
      sha256 "14df083dce9354acf3dcf9e81e966c4d6381bd3339acc662b828d3ac456ec668"

      def install
        bin.install "tfvm"
      end
    end
  end

  test do
    system "#{bin}/tfvm --help"
  end
end
