# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfvm < Formula
  desc "A Terraform Version Manager written in Go"
  homepage "https://github.com/ethanhassett/tfvm/tree/main"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethanhassett/tfvm-test/releases/download/v1.2.1/tfvm_1.2.1_darwin_amd64.tar.gz"
      sha256 "06f83773f008d3952d8a5e4c925005f905dba277468c5d5fa0e9195521800dbe"

      def install
        bin.install "tfvm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethanhassett/tfvm-test/releases/download/v1.2.1/tfvm_1.2.1_darwin_arm64.tar.gz"
      sha256 "fac6b6e9c958be2faa7d92375eaceae542d11138940e39ac6ec09b37e2031ff7"

      def install
        bin.install "tfvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanhassett/tfvm-test/releases/download/v1.2.1/tfvm_1.2.1_linux_arm64.tar.gz"
      sha256 "8c93af3359bda4cc22a87ba129b78ba229248808c05d392f5c9ffb61de08908b"

      def install
        bin.install "tfvm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ethanhassett/tfvm-test/releases/download/v1.2.1/tfvm_1.2.1_linux_amd64.tar.gz"
      sha256 "db97e8d392fbf8b6386adc01391c52d0ce79a6d61699b5e6d83a914df85fa08d"

      def install
        bin.install "tfvm"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ethanhassett/tfvm-test/releases/download/v1.2.1/tfvm_1.2.1_linux_armv6.tar.gz"
      sha256 "8a234d9b20a4debc526d86f50830a140cf452ea4f210522281bebed3f7f90b47"

      def install
        bin.install "tfvm"
      end
    end
  end

  test do
    system "#{bin}/tfvm --help"
  end
end
